### ISSUE TITLE
Fix for building with new binutils/gcc-12

### ISSUE THREAD

**Issue by colemickens** [revyos/thead-opensbi#1]
Hi, similar to this pull request: https://github.com/revyos/thead-u-boot/pull/11

Is it possible to fix up openSBI so that it builds with new binutils/gcc as well?

```
 CC        lib/sbi/sbi_platform.o
 CC        lib/sbi/sbi_scratch.o
 CC        lib/sbi/sbi_string.o
 CC        lib/sbi/sbi_system.o
 CC        lib/sbi/sbi_timer.o
 CC        lib/sbi/sbi_tlb.o
/build/source/lib/sbi/sbi_tlb.c: Assembler messages:
/build/source/lib/sbi/sbi_tlb.c:187: Error: unrecognized opcode `fence.i', extension `zifencei' required
make: *** [Makefile:339: /build/source/build/lib/sbi/sbi_tlb.o] Error 1
```

```extension `zifencei' required```

**Comment by colemickens** [comment]
Maybe this: https://github.com/riscv-software-src/opensbi/commit/5d53b55aa77ffeefd4012445dfa6ad3535e1ff2c

**Comment by RevySR** [comment]
Ok, I will cherry-pick it

**Comment by RevySR** [comment]
https://github.com/revyos/thead-opensbi/commit/0c27ac7f5dde5ccef92a45239c8203cc769beec6
